services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: boilerplate_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - boilerplate_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate_app
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - boilerplate_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: boilerplate_pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - boilerplate_net

  redis:
    image: redis:alpine
    container_name: boilerplate_redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - boilerplate_net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  boilerplate_net:
    driver: bridge

volumes:
  pgdata:
    driver: local
