FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --force

# Copy the rest of the application code
COPY . .

# RUN npm run build

RUN npx prisma generate
RUN npx prisma migrate deploy
RUN npx prisma migrate status

EXPOSE 5000

CMD ["npm", "run", "dev"]