version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-practice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - '8080:8080'

volumes:
  mysql_data:
